### ISSUE TITLE
Contact Create endpoint Duplicate Errors Need to be Disabled or Non-Blocking

### ISSUE THREAD

**Issue by CritiqalPete** [AmericaSCORESBayArea/salesforce-data-api#114] opened 2021-09-14 00:10 UTC
This is part of a multi-part overhall of the the Contact workflow for external apps.
Presently the API returns an error after performing a search for duplicated.

For the time being and until review we need do stop this and allow records to be created/updated anyway.

**Comment by matthewjerome** [comment] 2021-09-14 00:23
Mulesoft Logs : 

```
20:07:33.484   09/13/2021   Worker-0   [MuleRuntime].uber.30: [salesforce-data-api].post:\contacts:application\json:salesforce-data-api-config.BLOCKING @1250467   DEBUG
event:c19269a0-14ef-11ec-a9e7-024d73fb4356 Receiving response from Salesforce. Arguments: {endpoint=https://americascoresbayarea--scoresqa.my.salesforce.com/services/Soap/u/48.0/00D530000008hhc, response=<?xml version=“1.0” encoding=“UTF-8"?><soapenv:Envelope xmlns:soapenv=“http://schemas.xmlsoap.org/soap/envelope/” xmlns=“urn:partner.soap.sforce.com” xmlns:xsi=“http://www.w3.org/2001/XMLSchema-instance” xmlns:sf=“urn:sobject.partner.soap.sforce.com”><soapenv:Header><LimitInfoHeader><limitInfo><current>65</current><limit>5000000</limit><type>API REQUESTS</type></limitInfo></LimitInfoHeader></soapenv:Header><soapenv:Body><createResponse><result><errors xsi:type=“DuplicateError”><message>Use one of these records?</message><statusCode>DUPLICATES_DETECTED</statusCode><duplicateResult><allowSave>true</allowSave><duplicateRule>Standard_Contact_Duplicate_Rule</duplicateRule><duplicateRuleEntityType>Contact</duplicateRuleEntityType><errorMessage>Use one of these records?</errorMessage><matchResults><entityType>Contact</entityType><matchEngine>FuzzyMatchEngine</matchEngine><matchRecords><fieldDiffs><difference>NULL</difference><name>npe01__WorkPhone__c</name></fieldDiffs><fieldDiffs><difference>DIFFERENT</difference><name>Email</name></fieldDiffs><fieldDiffs><difference>NULL</difference><name>HomePhone</name></fieldDiffs><fieldDiffs><difference>DIFFERENT</difference><name>FirstName</name></fieldDiffs><fieldDiffs><difference>NULL</difference><name>Phone</name></fieldDiffs><fieldDiffs><difference>NULL</difference><name>npe01__HomeEmail__c</name></fieldDiffs><fieldDiffs><difference>SAME</difference><name>LastName</name></fieldDiffs><fieldDiffs><difference>NULL</difference><name>npe01__AlternateEmail__c</name></fieldDiffs><fieldDiffs><difference>NULL</difference><name>MailingStreet</name></fieldDiffs><fieldDiffs><difference>NULL</difference><name>npe01__WorkEmail__c</name></fieldDiffs><matchConfidence>87.0</matchConfidence><record xsi:type=“sf:sObject”><sf:type>Contact</sf:type><sf:Id>0031T00004GPGfHQAX</sf:Id><sf:Name>Matt Kern</sf:Name><sf:npe01__HomeEmail__c>matt@matt.com</sf:npe01__HomeEmail__c><sf:npe01__WorkPhone__c xsi:nil=“true”/><sf:npe01__AlternateEmail__c xsi:nil=“true”/><sf:npe01__WorkEmail__c xsi:nil=“true”/><sf:Email>matt@matt.com</sf:Email><sf:HomePhone xsi:nil=“true”/><sf:Phone xsi:nil=“true”/><sf:OwnerId>0051T000009eHfvQAE</sf:OwnerId><sf:LastModifiedDate>2021-08-17T23:17:34.000Z</sf:LastModifiedDate><sf:Id>0031T00004GPGfHQAX</sf:Id></record></matchRecords><rule>Name_only_or_Phone_Street_Rule</rule><size>1</size><success>true</success></matchResults></duplicateResult></errors><id xsi:nil=“true”/><success>false</success></result></createResponse></soapenv:Body></soapenv:Envelope>}.
20:07:33.521   09/13/2021   Worker-0   [MuleRuntime].uber.30: [salesforce-data-api].post:\contacts:application\json:salesforce-data-api-config.BLOCKING @1250467   DEBUG
event:c19269a0-14ef-11ec-a9e7-024d73fb4356 Execute over partner client - connection pool check in.
20:07:33.607   09/13/2021   Worker-0   [MuleRuntime].uber.30: [salesforce-data-api].post:\contacts:application\json:salesforce-data-api-config.BLOCKING @1250467   INFO
event:c19269a0-14ef-11ec-a9e7-024d73fb4356 Fuzzy contact match found
20:07:33.623   09/13/2021   Worker-0   [MuleRuntime].uber.29: [salesforce-data-api].post:\contacts:application\json:salesforce-data-api-config.CPU_INTENSIVE @4b81acba   ERROR
event:c19269a0-14ef-11ec-a9e7-024d73fb4356 ******************************************************************************** Message : An error occurred. Element : post:\contacts:application\json:salesforce-data-api-config/processors/5/route/0/processors/3/route/0/processors/2 @ salesforce-data-api:salesforce-data-api.xml:669 (Raise error) Element DSL : <raise-error doc:name=“Raise error” doc:id=“2870caa8-0d15-4067-8910-2d753a5f0a0c” type=“CREATECONTACT:CONFLICT”></raise-error> Error type : CREATECONTACT:CONFLICT FlowStack : at post:\contacts:application\json:salesforce-data-api-config(post:\contacts:application\json:salesforce-data-api-config/processors/5/route/0/processors/3/route/0/processors/2 @ salesforce-data-api:salesforce-data-api.xml:669 (Raise error)) at salesforce-data-api-main(salesforce-data-api-main/processors/0 @ salesforce-data-api:salesforce-data-api.xml:48) Payload Type : org.mule.runtime.core.internal.streaming.bytes.ManagedCursorStreamProvider --------------------------------------------------------------------------------
8:10
Root Exception stack trace: org.mule.runtime.api.exception.DefaultMuleException: An error occurred. at org.mule.runtime.core.api.processor.RaiseErrorProcessor.process(RaiseErrorProcessor.java:64) at org.mule.runtime.core.api.util.func.CheckedFunction.apply(CheckedFunction.java:25) at org.mule.runtime.core.api.rx.Exceptions.lambda$checkedFunction$2(Exceptions.java:85) at org.mule.runtime.core.internal.util.rx.Operators.lambda$nullSafeMap$0(Operators.java:47) at reactor.core.publisher.FluxHandleFuseable$HandleFuseableSubscriber.onNext(FluxHandleFuseable.java:165) at org.mule.runtime.core.privileged.processor.chain.AbstractMessageProcessorChain$2.onNext(AbstractMessageProcessorChain.java:432) at org.mule.runtime.core.privileged.processor.chain.AbstractMessageProcessorChain$2.onNext(AbstractMessageProcessorChain.java:427) at reactor.core.publisher.FluxHide$SuppressFuseableSubscriber.onNext(FluxHide.java:127) at reactor.core.publisher.FluxPeekFuseable$PeekFuseableSubscriber.onNext(FluxPeekFuseable.java:204) at reactor.core.publisher.FluxOnAssembly$OnAssemblySubscriber.onNext(FluxOnAssembly.java:345) at reactor.core.publisher.FluxPeekFuseable$PeekFuseableSubscriber.onNext(FluxPeekFuseable.java:204) at reactor.core.publisher.FluxContextStart$ContextStartSubscriber.onNext(FluxContextStart.java:103) at reactor.core.publisher.FluxContextStart$ContextStartSubscriber.onNext(FluxContextStart.java:103) at reactor.core.publisher.FluxMap$MapConditionalSubscriber.onNext(FluxMap.java:213) at reactor.core.publisher.MonoFlatMapMany$FlatMapManyInner.onNext(MonoFlatMapMany.java:242) at reactor.core.publisher.FluxFlatMap$FlatMapMain.tryEmit(FluxFlatMap.java:532) at reactor.core.publisher.FluxFlatMap$FlatMapInner.onNext(FluxFlatMap.java:974) at reactor.core.publisher.FluxContextStart$ContextStartSubscriber.onNext(FluxContextStart.java:103) at reactor.core.publisher.MonoNext$NextSubscriber.onNext(MonoNext.java:76) at org.mule.runtime.core.privileged.processor.chain.AbstractMessageProcessorChain$2.onNext(AbstractMessageProcessorChain.java:432) at org.mule.runtime.core.privileged.processor.chain.AbstractMessageProcessorChain$2.onNext(AbstractMessageProcessorChain.java:427) at reactor.core.publisher.FluxHandleFuseable$HandleFuseableSubscriber.onNext(FluxHandleFuseable.java:180) at org.mule.runtime.core.privileged.processor.chain.AbstractMessageProcessorChain$2.onNext(AbstractMessageProcessorChain.java:432) at org.mule.runtime.core.privileged.processor.chain.AbstractMessageProcessorChain$2.onNext(AbstractMessageProcessorChain.java:427) at reactor.core.publisher.FluxHide$SuppressFuseableSubscriber.onNext(FluxHide.java:127) at reactor.core.publisher.FluxPeekFuseable$PeekFuseableSubscriber.onNext(FluxPeekFuseable.java:204) at reactor.core.publisher.FluxOnAssembly$OnAssemblySubscriber.onNext(FluxOnAssembly.java:345) at reactor.core.publisher.FluxSubscribeOnValue$ScheduledScalar.run(FluxSubscribeOnValue.java:178) at reactor.core.scheduler.SchedulerTask.call(SchedulerTask.java:50) at reactor.core.scheduler.SchedulerTask.call(SchedulerTask.java:27) at java.util.concurrent.FutureTask.run(FutureTask.java:266) at org.mule.service.scheduler.internal.AbstractRunnableFutureDecorator.doRun(AbstractRunnableFutureDecorator.java:111) at org.mule.service.scheduler.internal.RunnableFutureDecorator.run(RunnableFutureDecorator.java:54) at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) at java.lang.Thread.run(Thread.java:748)
```

**Comment by AleksandrMolchagin** [comment] 2024-05-29 19:27
Duplicate of #124, already implemented.

**Closed by AleksandrMolchagin** 2024-05-29 19:27 UTC
Labels: bug, Critical/Blocking
